### ISSUE TITLE
Modify installation instructions in readme

### ISSUE THREAD

**Issue by DinoCapocchiano** [mellesies/vtg.coxph#1]
I think there is small mistake in the installation instructions. For it to work you need to change this:

```
# This also installs the package vantage.infrastructure
devtools::install_github('mellesies/vtg.coxph')
```
into this:
```
devtools::install_github('mellesies/vtg.coxph', subdir="src")
```
because you put the package files into that subdir.

**Comment by mellesies** [comment]
Good catch! Thanks!
Have updated the README.
